language: node_js
node_js:
  - "14"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run test
  - npm run lint
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
